# Generated by Django 4.1.4 on 2023-01-26 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontdesk", "0003_alter_carenquiresmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carenquiresmodel",
            name="user_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number should be 10 digits", regex="^\\d{10}$"
                    )
                ],
            ),
        ),
    ]
