# Generated by Django 4.1.4 on 2023-01-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universal_car_number', models.CharField(max_length=100)),
                ('first_service_km', models.IntegerField()),
                ('first_service_month', models.IntegerField()),
                ('second_service_km', models.IntegerField()),
                ('second_service_month', models.IntegerField()),
                ('third_service_km', models.IntegerField()),
                ('third_service_month', models.IntegerField()),
                ('number_of_free_services', models.IntegerField()),
                ('base_fee', models.IntegerField()),
            ],
        ),
    ]
