# Generated by Django 4.1.4 on 2023-01-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='universal_car_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
