# Generated by Django 4.1.4 on 2023-01-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0024_alter_cars_universal_car_number_and_more'),
        ('services', '0005_serviceinfo_afterwards_service_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_car', to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='services',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
