# Generated by Django 4.1.4 on 2023-01-25 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0011_baycurrentjob_bay_baydetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='baydetails',
            name='mechanic_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bay_mechanic_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('assigned', 'assigned'), ('in-bay', 'in-bay'), ('finished', 'finished')], max_length=100),
        ),
    ]
