# Generated by Django 4.1.4 on 2023-01-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_carparts_labour_charge_carparts_price'),
        ('services', '0012_baydetails_mechanic_1_alter_services_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='parts_used',
            field=models.ManyToManyField(to='cars.carparts'),
        ),
        migrations.AlterField(
            model_name='baycurrentjob',
            name='bay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_bay', to='services.baydetails'),
        ),
    ]
