# Generated by Django 4.1.4 on 2023-01-26 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0033_alter_cars_uni_car_part_num_and_more"),
        ("services", "0013_services_parts_used_alter_baycurrentjob_bay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baycurrentjob",
            name="bay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_bay",
                to="services.baydetails",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_car",
                to="cars.cars",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
