# Generated by Django 4.1.4 on 2023-01-27 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0014_alter_baycurrentjob_bay_alter_services_car_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "requested"),
                    ("assigned", "assigned"),
                    ("in-bay", "in-bay"),
                    ("billing", "billing"),
                    ("finished", "finished"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ServiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("is_free", models.BooleanField()),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.services",
                    ),
                ),
            ],
        ),
    ]
