# Generated by Django 4.1.4 on 2023-01-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0016_alter_servicehistory_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
