# Generated by Django 4.1.4 on 2023-01-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0017_services_is_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicehistory",
            name="labour_charge",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicehistory",
            name="parts_total",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
