# Generated by Django 4.1.4 on 2023-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0020_baycurrentjob_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="baycurrentjob",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
