# Generated by Django 4.1.4 on 2023-01-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0021_baycurrentjob_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="baycurrentjob",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
