# Generated by Django 4.1.4 on 2022-12-17 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_year', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('chase_number', models.CharField(max_length=200)),
                ('engine_number', models.CharField(max_length=200)),
                ('seat_capacity', models.IntegerField()),
                ('gear_type', models.CharField(max_length=100)),
                ('gear_count', models.CharField(max_length=50)),
                ('engine_cc', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('engine_power', models.CharField(max_length=100)),
                ('engine_torque', models.CharField(max_length=100)),
                ('wheel_base', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
