# Generated by Django 4.1.4 on 2022-12-17 06:05

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_year', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('chase_number', models.CharField(max_length=200)),
                ('engine_number', models.CharField(max_length=200)),
                ('seat_capacity', models.IntegerField()),
                ('gear_type', models.CharField(max_length=100)),
                ('gear_count', models.CharField(max_length=50)),
                ('engine_cc', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('engine_power', models.CharField(max_length=100)),
                ('engine_torque', models.CharField(max_length=100)),
                ('wheel_base', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.models.nameFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])])),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
