# Generated by Django 4.1.4 on 2022-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_displaycars_cars_is_active_cars_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
