# Generated by Django 4.1.4 on 2022-12-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cars_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.CharField(default=100000, max_length=100),
        ),
    ]
