# Generated by Django 4.1.4 on 2022-12-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='gear_type',
            field=models.CharField(choices=[('AMT', 'AMT'), ('Manual', 'Manual'), ('DCT', 'DCT')], max_length=100),
        ),
    ]
