# Generated by Django 4.1.4 on 2022-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_cars_gear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='chase_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback')], max_length=50, null=True),
        ),
    ]
