# Generated by Django 4.1.4 on 2022-12-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cars_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaycars',
            name='chase_number',
        ),
        migrations.RemoveField(
            model_name='displaycars',
            name='engine_number',
        ),
    ]
