# Generated by Django 4.1.4 on 2022-12-31 14:00

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_displaycars_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaycars',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=cars.models.nameFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='displaycars',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=cars.models.nameFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
    ]
