# Generated by Django 4.1.4 on 2023-01-03 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_displaycars_image1_displaycars_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaycars',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
