# Generated by Django 4.1.4 on 2023-01-12 17:28

import cars.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_displaycars_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.models.nameFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.displaycars')),
            ],
        ),
    ]
