# Generated by Django 4.1.4 on 2023-01-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_displaycarimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaycars',
            name='image',
        ),
        migrations.RemoveField(
            model_name='displaycars',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='displaycars',
            name='image3',
        ),
        migrations.AlterField(
            model_name='displaycarimages',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_image', to='cars.displaycars'),
        ),
    ]
