# Generated by Django 4.1.4 on 2023-01-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_remove_displaycars_image_remove_displaycars_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaycarimages',
            name='car',
        ),
    ]
