# Generated by Django 4.1.4 on 2023-01-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_remove_displaycarimages_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaycars',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.displaycarimages'),
        ),
    ]
