# Generated by Django 4.1.4 on 2023-01-13 05:34

import cars.models
import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_displaycars_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaycars',
            name='images',
        ),
        migrations.AddField(
            model_name='displaycarimages',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.CharField, to='cars.displaycars'),
        ),
        migrations.AlterField(
            model_name='displaycarimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cars.models.namePicFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
    ]
