# Generated by Django 4.1.4 on 2023-01-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_cars_universal_car_number_cars_universal_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='universal_car_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='universal_part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
