# Generated by Django 4.1.4 on 2023-01-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_alter_cars_universal_car_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='delivered_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
