# Generated by Django 4.1.4 on 2023-01-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_cars_delivered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_part_name', models.CharField(max_length=200)),
                ('compatible_cars', models.ManyToManyField(to='cars.cars')),
            ],
        ),
    ]
