# Generated by Django 4.1.4 on 2023-01-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_carparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparts',
            name='stock',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
