# Generated by Django 4.1.4 on 2023-01-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_carparts_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniPartNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universal_car_part_number', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='uni_car_part_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unicarpartnum', to='cars.unipartnumbers'),
        ),
    ]
