# Generated by Django 4.1.4 on 2023-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_unipartnumbers_cars_uni_car_part_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='delivered_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
