# Generated by Django 4.1.4 on 2023-01-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_alter_carparts_compatible_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparts',
            name='labour_charge',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carparts',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
