# Generated by Django 4.1.4 on 2023-01-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0032_carparts_labour_charge_carparts_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="uni_car_part_num",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unicarpartnum",
                to="cars.unipartnumbers",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="universal_car_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cars",
            name="universal_part_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cars",
            name="verified_by",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="displaycarimages",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carimg",
                to="cars.displaycars",
            ),
        ),
    ]
